name: Publish

on:
  push:
    branches:
      - production

permissions:
  contents: write
    
jobs:
  build:
    runs-on: macos-14

    steps:

    - uses: actions/checkout@v4

    - uses: subosito/flutter-action@v2
      with:
        channel: stable

    - run: flutter pub get
    
    - run: flutter build macos

    - run: zip -r build/macos/Build/Products/Release/stash_app.app.zip build/macos/Build/Products/Release/stash_app.app

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/macos/Build/Products/Release/stash_app.app.zip
        asset_name: stash-admin-macos.zip
        tag: 'latest-macos'
        overwrite: true
        body: "Automatic release"
